spring:
  application:
    name: customer-service
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 500ms
      additional-paths: /workspace/src
    livereload:
      enabled: true
      port: 35729
server:
  port: ${PORT:8080}
